Loading checkpoint shards:  38%|█████████████████████████▌                                          | 3/8 [00:08<00:14,  2.92s/it]
Traceback (most recent call last):
  File "train.py", line 82, in <module>
    main(args)
  File "train.py", line 32, in main
    model, tokenizer = load_model_and_tokenizer(args.model_id, device_string, args.quantization_bits)
  File "/home/llm4math/LLM-for-Math/Direct Verifier/code/model/load_model.py", line 6, in load_model_and_tokenizer
    model = AutoModelForCausalLM.from_pretrained(model_id,  device_map={"": device_string}, quantization_config=quantization_config)
  File "/home/llm4math/miniconda3/envs/mathllm/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
  File "/home/llm4math/miniconda3/envs/mathllm/lib/python3.8/site-packages/transformers/modeling_utils.py", line 4225, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/llm4math/miniconda3/envs/mathllm/lib/python3.8/site-packages/transformers/modeling_utils.py", line 4728, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/home/llm4math/miniconda3/envs/mathllm/lib/python3.8/site-packages/transformers/modeling_utils.py", line 995, in _load_state_dict_into_meta_model
    hf_quantizer.create_quantized_param(model, param, param_name, param_device, state_dict, unexpected_keys)
  File "/home/llm4math/miniconda3/envs/mathllm/lib/python3.8/site-packages/transformers/quantizers/quantizer_bnb_4bit.py", line 238, in create_quantized_param
    new_value = bnb.nn.Params4bit(new_value, requires_grad=False, **kwargs).to(target_device)
  File "/home/llm4math/miniconda3/envs/mathllm/lib/python3.8/site-packages/bitsandbytes/nn/modules.py", line 331, in to
    return self._quantize(device)
  File "/home/llm4math/miniconda3/envs/mathllm/lib/python3.8/site-packages/bitsandbytes/nn/modules.py", line 295, in _quantize
    w = self.data.contiguous().to(device)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 98.00 MiB. GPU 1 has a total capacity of 47.43 GiB of which 86.50 MiB is free. Process 786375 has 43.14 GiB memory in use. Including non-PyTorch memory, this process has 4.12 GiB memory in use. Of the allocated memory 3.69 GiB is allocated by PyTorch, and 133.60 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
